### PR TITLE
Fix to errors TS2684 and TS2345, when running `tsc --pretty`

### PR DESCRIPTION
**Pull request by FelipeCalliari**
When running `npm run build`, the `tsc --pretty` outputs the following errors:

```
> twitch_drops_bot@1.2.2 compile
> tsc --pretty

src/pages/login.ts:119:35 - error TS2684: The 'this' context of type 'ElementHandle<Node>' is not assignable to method's 'this' of type 'ElementHandle<Element>'.

119                             await resendCodeButton.click();
                                      ~~~~~~~~~~~~~~~~

src/pages/login.ts:131:27 - error TS2684: The 'this' context of type 'ElementHandle<Node>' is not assignable to method's 'this' of type 'ElementHandle<Element>'.

131                     await first_input.click();
                              ~~~~~~~~~~~

src/pages/login.ts:158:27 - error TS2684: The 'this' context of type 'ElementHandle<Node>' is not assignable to method's 'this' of type 'ElementHandle<Element>'.

158                     await first_input.click();
                              ~~~~~~~~~~~

src/pages/login.ts:167:27 - error TS2684: The 'this' context of type 'ElementHandle<Node>' is not assignable to method's 'this' of type 'ElementHandle<Element>'.

167                     await button.click();
                              ~~~~~~

src/stream_watcher.ts:86:56 - error TS2345: Argument of type 'ElementHandle<Node>' is not assignable to parameter of type 'ElementHandle<Element>'.

86             await waitUntilElementRendered(this.#page, element); //todo: timout
                                                          ~~~~~~~

src/twitch_drops_bot.ts:1305:62 - error TS2345: Argument of type 'ElementHandle<Node>' is not assignable to parameter of type 'ElementHandle<Element>'.
  Type 'Node' is missing the following properties from type 'Element': attributes, classList, className, clientHeight, and 110 more.

1305             await this.#waitUntilElementRendered(this.#page, element);
                                                                  ~~~~~~~


Found 6 errors in 3 files.

Errors  Files
     4  src/pages/login.ts:119
     1  src/stream_watcher.ts:86
     1  src/twitch_drops_bot.ts:1305
```

These changes fix this problem.

### CODE REVIEW

**Comment by TychoTheTaco** [comment]
Thanks for the contribution! Some comments before I merge this:
1. `react` and `@types/react` can't be updated yet because `ink` doesn't support version 18 yet.
2. You don't need to add comments with each of your changes. It adds some unneeded clutter to keep the old code commented out. This PR already serves as the documentation for the changes.

**Comment by FelipeCalliari** [comment]
Ok, thanks for the feedback.

I didn't know about `react`, `@types/react` and `ink`. Sorry.
If you want I can change the source files and remove the comments.

Thank you for maintaining and supporting this project.

**Comment by TychoTheTaco** [comment]
Yes, please update the PR according to comments.

**Review by FelipeCalliari — COMMENTED** [review]
Removed the comments and reverted "react" and "@types/react" versions.

**Pull request merged**
